steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/bokeh-app-image", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/bokeh-app-image"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args: [
        "run",
        "deploy",
        "bokeh-demo-app-service-1", # change to your service name
        "--image",
        "gcr.io/$PROJECT_ID/bokeh-app-image",
        "--max-instances",
        "1",
        "--memory",
        "128M",
        "--concurrency",
        "80",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]
images:
  - gcr.io/$PROJECT_ID/bokeh-app-image
